#!/bin/bash

# Quick Setup Guide for Student Login Improvements
# This script helps you test the new login/logout features

echo "🎓 NEET Academy - Student Login Improvements"
echo "=============================================="
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this from the project root directory"
    exit 1
fi

echo "📦 Installation Steps:"
echo "1. Backend setup"
echo "2. Frontend setup"
echo "3. Testing checklist"
echo ""

# Backend
echo "🔧 Backend Setup"
echo "==============="
cd backend
echo "✓ Installing backend dependencies..."
npm install 2>/dev/null || echo "⚠️  npm install skipped"

echo ""
echo "✓ Check .env file has:"
echo "   - JWT_SECRET=your-secure-key"
echo "   - NODE_ENV=production (for testing)"
echo ""

# Frontend  
echo "🎨 Frontend Setup"
echo "================"
cd ../client
echo "✓ Installing frontend dependencies..."
npm install 2>/dev/null || echo "⚠️  npm install skipped"

echo ""
echo "✓ Verify react-icons is installed (for Feather icons)"
npm ls react-icons 2>/dev/null | head -5

echo ""
echo "✅ Setup Complete!"
echo ""
echo "📝 Testing Checklist:"
echo "===================="
echo ""
echo "□ Login Features:"
echo "  □ Password strength indicator updates in real-time"
echo "  □ Show/hide password toggle works"
echo "  □ 'Remember me' saves student ID"
echo "  □ Error messages are helpful and clear"
echo ""
echo "□ Security Features:"
echo "  □ Try 5 wrong passwords → account locks for 5 minutes"
echo "  □ Lockout countdown timer displays"
echo "  □ Correct password clears the lockout"
echo ""
echo "□ 3D Effects:"
echo "  □ Particle background animation is smooth"
echo "  □ Login card has hover effects"
echo "  □ Logout dialog is beautiful with animations"
echo ""
echo "□ Dashboard Features:"
echo "  □ Session timer counts up in real-time"
echo "  □ Student info displays correctly"
echo "  □ Tab switching works smoothly"
echo "  □ Security badge is visible"
echo ""
echo "□ Session Management:"
echo "  □ Inactive for 25 mins → see warning banner"
echo "  □ Warning shows countdown timer"
echo "  □ Click 'Stay Active' resets timeout"
echo "  □ After 30 mins → auto logout"
echo ""
echo "□ Logout:"
echo "  □ Click logout → beautiful confirmation dialog"
echo "  □ Dialog shows session duration"
echo "  □ Confirm logout → redirects to home"
echo "  □ Cancel → returns to dashboard"
echo ""
echo "🚀 Running the Application:"
echo "============================"
echo ""
echo "Terminal 1 - Backend:"
echo "  cd backend && npm start"
echo "  (should start on http://localhost:5000)"
echo ""
echo "Terminal 2 - Frontend:"
echo "  cd client && npm start"
echo "  (should open http://localhost:3000)"
echo ""
echo "🧪 Quick Test Credentials:"
echo "=========================="
echo "Ask your admin for test student credentials"
echo ""
echo "📊 What Changed?"
echo "================="
echo "Files Modified:"
echo "  • client/src/pages/StudentLogin.jsx"
echo "  • client/src/pages/StudentDashboard.jsx"
echo "  • backend/controllers/studentController.js"
echo "  • backend/routes/studentRoutes.js"
echo ""
echo "New Files:"
echo "  • client/src/utils/sessionManager.js"
echo "  • STUDENT_LOGIN_IMPROVEMENTS.md"
echo "  • LOGIN_LOGOUT_SUMMARY.md"
echo ""
echo "💡 Pro Tips:"
echo "============"
echo "• Use F12 → Console to check for any errors"
echo "• Check Network tab to verify API calls"
echo "• Open DevTools → Application to see localStorage"
echo "• Test on mobile device for responsive design"
echo ""
echo "📚 Documentation:"
echo "================"
echo "For detailed info, read:"
echo "  • STUDENT_LOGIN_IMPROVEMENTS.md (comprehensive guide)"
echo "  • LOGIN_LOGOUT_SUMMARY.md (feature summary)"
echo ""
echo "🎯 Security Notes:"
echo "=================="
echo "• Always use HTTPS in production"
echo "• Keep JWT_SECRET strong and secret"
echo "• Review server logs for suspicious login attempts"
echo "• Test with various edge cases"
echo ""
echo "❓ Issues?"
echo "=========="
echo "1. Check backend is running on port 5000"
echo "2. Check frontend .env has correct API_BASE_URL"
echo "3. Clear browser cache (Ctrl+Shift+Delete)"
echo "4. Check browser console for errors"
echo "5. Look for console errors in both frontend and backend"
echo ""
echo "✨ Ready to test! Good luck! 🚀"
